apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-consumer
  labels:
    app: {{ .Chart.Name }}-consumer
    component: data-processor
spec:
  replicas: {{ .Values.consumer.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-consumer
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-consumer
        component: data-processor
    spec:
      containers:
      - name: consumer
        image: {{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}
        imagePullPolicy: {{ .Values.consumer.image.pullPolicy }}
        
        resources:
          {{- toYaml .Values.consumer.resources | nindent 10 }}
        
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ .Values.consumer.kafka.bootstrapServers | quote }}
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TOPIC_NAME
          value: {{ .Values.consumer.kafka.topic | quote }}
