apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-inference
  labels:
    app: {{ .Chart.Name }}-inference
spec:
  type: {{ .Values.inference.service.type }}
  selector:
    app: {{ .Chart.Name }}-inference
  ports:
  - name: http
    port: {{ .Values.inference.service.port }}
    targetPort: {{ .Values.inference.service.port }}
    protocol: TCP
