apiVersion: v1
kind: Service
metadata:
  name: sentinel-inference
  labels:
    app: sentinel-inference
spec:
  type: ClusterIP
  selector:
    app: sentinel-inference
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
